import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { WorkerProvider } from "@/app/context/chat-worker-context";
import { Navbar } from "@/components/navbar";
import { AuthProvider } from "./contexts/auth.context";
import { MedicalRecordsProvider } from "./contexts/medical-record.context";
import { Footer } from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider>
          <Navbar />
          <MedicalRecordsProvider>
            <WorkerProvider>{children}</WorkerProvider>
          </MedicalRecordsProvider>
          <Footer />
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
